project/app/urls.py
from django.urls import path

from app import views
from app.views import PanelView, MenuView, CategoryView, DishView, UserView, CategoryUpdateView, DishUpdateView, \
    CategoryDetailView, DishDetailView, CategoryCreateView, CategoryDeleteView, DishCreateView, DishDeleteView

urlpatterns = [
    path('panel/', PanelView.as_view(), name='panel'),
    path('menu/', MenuView.as_view(), name='menu'),
    path('category/', CategoryView.as_view(), name='category'),
    path('dish/', DishView.as_view(), name='dish'),
    path('user/', UserView.as_view(), name='user'),
    path('edit_category/<int:pk>/', CategoryUpdateView.as_view(), name='edit_category'),
    path('edit_dish/<int:pk>/', DishUpdateView.as_view(), name='edit_dish'),
    path('detail_category/<int:pk>/', CategoryDetailView.as_view(), name='detail_category'),
    path('detail_dish/<int:pk>/', DishDetailView.as_view(), name='detail_dish'),
    path('create_category/', CategoryCreateView.as_view(), name='create_category'),
    path('delete_category/<int:pk>/', CategoryDeleteView.as_view(), name='delete_category'),
    path('create_dish/', DishCreateView.as_view(), name='create_dish'),
    path('delete_dish/<int:pk>/', DishDeleteView.as_view(), name='delete_dish'),
    path('add_to_basket/<int:dish_id>/', views.add_to_basket, name='add_to_basket'),
    path('basket/', views.basket_view, name='basket'),
    path('create-order/', views.create_order, name='create_order'),
    path('order-confirmation/', views.order_confirmation, name='order_confirmation'),
    path('basket/decrease/<int:item_id>/', views.decrease_quantity_in_basket, name='decrease_quantity_in_basket'),
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('', include('user.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/user/urls.py
from django.urls import path

from user.views import CustomLoginView, RegisterView, LogoutView

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

project/app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='dishes')
    price = models.PositiveIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Order by {self.user.username}"


class OrderElement(models.Model):
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    dish_quantity = models.PositiveIntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.dish.name} x {self.dish_quantity}"


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    dish_quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.user.username}'s basket: {self.dish.name} x {self.dish_quantity}"


project/user/models.py
from django.db import models

# Create your models here.

project/user/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView


class CustomLoginView(LoginView):
    template_name = 'user/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        if self.request.user.is_staff:
            return reverse_lazy('panel')
        else:
            return reverse_lazy('menu')


class RegisterView(FormView):
    template_name = 'user/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('menu')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        if user.is_staff:
            return redirect('panel')
        else:
            return redirect('menu')


class LogoutView(LogoutView):
    next_page = reverse_lazy('login')

project/app/templates/app/admin/category.html

{% extends 'app/layouts/base.html' %}
{% load static %}

{% block title %}Категории{% endblock %}

{% block content %}

<div class="container_category">
    <h2>Категории</h2>
    <div class="add_category"><a href="{% url 'create_category' %}">Добавить категорию</a></div>
    <div class="back"><a href="{% url 'panel' %}">Назад</a></div>
    <div class="category">
    <div>
        {% for category in categories %}
            <div class="category_options">
                <div class="category_name">{{ category.name }}</div>
                <div><a href="{% url 'detail_category' category.id %}">Подробнее</a></div>
                <div><a href="{% url 'edit_category' category.id %}">Редактировать</a></div>
                <div><a href="{% url 'delete_category' category.id %}">Удалить</a></div>
            </div>

        {% empty %}
            Категорий нет
        {% endfor %}
    </div>

    </div>
</div>


{% endblock %}

project/app/templates/app/admin/create_category.html
{% extends 'app/layouts/base.html' %}

{% load static %}
{% block title %}Создание категории{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

project/app/templates/app/admin/create_dish.html
{% extends 'app/layouts/base.html' %}

{% load static %}

{% block title %}Создание блюда{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

project/app/templates/app/admin/delete_category.html
{% extends 'app/layouts/base.html' %}

{% load static %}

{% block title %}Удаление категории{% endblock %}

{% block content %}
<div class="delete_category">
    <h2>Вы действительно хотите удалить категорию {{ category.name }}?</h2>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
    </form>
    <div class="back"><a href="{% url 'category' %}">Назад</a></div>
</div>
{% endblock %}

project/app/templates/app/admin/delete_dish.html
{% extends 'app/layouts/base.html' %}

{% load static %}

{% block title %}Удаление блюда{% endblock %}

{% block content %}
<div class="delete_dish">
    <h2>Вы действительно хотите удалить блюдо {{ dish.name }}?</h2>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
    </form>
    <div class="back"><a href="{% url 'dish' %}">Назад</a></div>
</div>
{% endblock %}

project/app/templates/app/admin/detail_category.html


{% extends 'app/layouts/base.html' %}
{% load static %}

{% block title %}Детали категории{% endblock %}


{% block content %}

<div class="container_detail_category">
    <h2>Детали категории</h2>
    <div class="back"><a href="{% url 'category' %}">Назад</a></div>
    <div>
        Name:{{ category.name }}
    </div>
    <div><a href="{% url 'edit_category' category.id %}">Редактировать</a></div>
</div>



{% endblock %}

project/app/templates/app/admin/detail_dish.html
{% extends 'app/layouts/base.html' %}
{% load static %}

{% block title %}Детали блюда{% endblock %}

{% block content %}
<div class="container_detail_dish">
    <h2>Детали блюда</h2>
    <div class="back"><a href="{% url 'dish' %}">Назад</a></div>
    <div>
        <div>Name: {{ dish.name }}</div>
        <div>
            Photo:
            {% if dish.photo %}
                <img src="{{ dish.photo.url }}" alt="Фото блюда" class="dish-photo">
            {% else %}
                Нет фото
            {% endif %}
        </div>
        <div>Price: {{ dish.price }}</div>
        <div>Category: {{ dish.category }}</div>
    </div>
    <div><a href="{% url 'edit_dish' dish.id %}">Редактировать</a></div>
</div>
{% endblock %}

project/app/templates/app/admin/dish.html

{% extends 'app/layouts/base.html' %}
{% load static %}

{% block title %}Блюда{% endblock %}

{% block content %}

<div class="container_dish">
    <h2>Блюда</h2>
    <div class="add_dish"><a href="{% url 'create_dish' %}">Добавить блюдо</a></div>
    <div class="back"><a href="{% url 'panel' %}">Назад</a></div>
    <div class="dish">
    <div>
        {% for dish in dishes %}
            <div class="dish_options">
                <div class="dish_name">{{ dish.name }}</div>
                <div><a href="{% url 'detail_dish' dish.id %}">Подробнее</a></div>
                <div><a href="{% url 'edit_dish' dish.id %}">Редактировать</a></div>
                <div><a href="{% url 'delete_dish' dish.id %}">Удалить</a></div>
            </div>

        {% empty %}
            Блюд нет
        {% endfor %}
    </div>

    </div>
</div>


{% endblock %}

project/app/templates/app/admin/edit_category.html
{% extends 'app/layouts/base.html' %}

{% load static %}

{% block title %}Редактирование категории{% endblock %}

{% block content %}

<div class="edit_category">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить">
    </form>
    <div class="back"><a href="{% url 'category' %}">Назад</a></div>
</div>


{% endblock %}

project/app/templates/app/admin/edit_dish.html
{% extends 'app/layouts/base.html' %}

{% load static %}

{% block title %}Редактирование блюда{% endblock %}

{% block content %}

<div class="edit_dish">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить">
    </form>
    <div class="back"><a href="{% url 'dish' %}">Назад</a></div>
</div>


{% endblock %}

project/app/templates/app/admin/panel.html
{% extends 'app/layouts/base.html' %}
{% load static %}

{% block title %}Панель управления{% endblock %}



{% block content %}
    <div class="container_panel">
        <div class="option_panel">
            <a href="{% url 'category' %}">
                Категории
            </a>
        </div>
        <div class="option_panel">
            <a href="{% url 'dish' %}">
                Блюда
            </a>
        </div>
        <div class="option_panel">
            <a href="{% url 'user' %}">
                Пользователи
            </a>

        </div>

    </div>
{% endblock %}

project/app/templates/app/admin/user.html
{% extends 'app/layouts/base.html' %}

{% load static %}

{% block title %}Пользователи и их заказы{% endblock %}

{% block content %}

<div class="container_user_orders">
    <h2>Пользователи</h2>
    <div class="back"><a href="{% url 'panel' %}">Назад</a></div>

    <div class="user_orders">
        {% for user in users %}
            <div class="user_block">
                <h3 class="user_name">{{ user.username }}</h3>

                <div class="orders">
                    <h4>Заказы:</h4>
                    <ul>
                        {% for order in orders %}
                            {% if order.user == user %}
                                <li>
                                    <strong>Заказ № {{ order.id }}:</strong>
                                    <ul>
                                        {% for order_element in order.orderelement_set.all %}
                                            <li>{{ order_element.dish.name }} x {{ order_element.dish_quantity }}</li>
                                        {% empty %}
                                            <li>Нет элементов в заказе</li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endif %}
                        {% empty %}
                            <li>Нет заказов</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}