project/app/urls.py
from django.urls import path

from app import views
from app.views import PanelView, MenuView, CategoryView, DishView, UserView, CategoryUpdateView, DishUpdateView, \
    CategoryDetailView, DishDetailView, CategoryCreateView, CategoryDeleteView, DishCreateView, DishDeleteView

urlpatterns = [
    path('panel/', PanelView.as_view(), name='panel'),
    path('menu/', MenuView.as_view(), name='menu'),
    path('category/', CategoryView.as_view(), name='category'),
    path('dish/', DishView.as_view(), name='dish'),
    path('user/', UserView.as_view(), name='user'),
    path('edit_category/<int:pk>/', CategoryUpdateView.as_view(), name='edit_category'),
    path('edit_dish/<int:pk>/', DishUpdateView.as_view(), name='edit_dish'),
    path('detail_category/<int:pk>/', CategoryDetailView.as_view(), name='detail_category'),
    path('detail_dish/<int:pk>/', DishDetailView.as_view(), name='detail_dish'),
    path('create_category/', CategoryCreateView.as_view(), name='create_category'),
    path('delete_category/<int:pk>/', CategoryDeleteView.as_view(), name='delete_category'),
    path('create_dish/', DishCreateView.as_view(), name='create_dish'),
    path('delete_dish/<int:pk>/', DishDeleteView.as_view(), name='delete_dish'),
    path('add_to_basket/<int:dish_id>/', views.add_to_basket, name='add_to_basket'),
    path('basket/', views.basket_view, name='basket'),
    path('create-order/', views.create_order, name='create_order'),
    path('order-confirmation/', views.order_confirmation, name='order_confirmation'),
    path('basket/decrease/<int:item_id>/', views.decrease_quantity_in_basket, name='decrease_quantity_in_basket'),
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('', include('user.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='dishes')
    price = models.PositiveIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Order by {self.user.username}"


class OrderElement(models.Model):
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    dish_quantity = models.PositiveIntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.dish.name} x {self.dish_quantity}"


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    dish_quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.user.username}'s basket: {self.dish.name} x {self.dish_quantity}"


project/app/templates/app/customer/basket.html
{% extends 'app/layouts/base.html' %}

{% block content %}
        <a href="{% url 'menu' %}" class="back_button">Назад в меню</a>
<h2>Корзина</h2>

<div class="basket_container">
    {% for item in basket_items %}
        <div class="basket_item dish_{{ item.dish.id }}">
            <p class="dish_name">{{ item.dish.name }} - {{ item.dish_quantity }} шт. - {{ item.total_price }} сум</p>
            <a href="{% url 'decrease_quantity_in_basket' item.id %}" class="decrease_button">-</a>
        </div>
    {% empty %}
        <p>Корзина пуста.</p>
    {% endfor %}

    {% if basket_items %}
        <div class="total_price_section">
            <p><strong>Общая стоимость:</strong> <span class="total_price">{{ total_price }} сум</span></p>
        </div>
        <div class="basket_buttons">
            <a href="{% url 'create_order' %}" class="order_button">Заказать</a>

        </div>
    {% endif %}
</div>
{% endblock %}



project/app/templates/app/customer/menu.html
{% extends 'app/layouts/base.html' %}
{% load static %}
{% block content %}
<div class="container_menu">
    <h2 class="menu_title">Menu</h2>
    <div class="basket_container">
        <div class="basket_btn"><a href="{% url 'basket' %}">Корзина</a></div>
    </div>
    <div class="menu_category_dish">
        {% for category in categories %}
            <div class="menu_dish_cards">
                <h3 class="menu_category_name">{{ category.name }}</h3>
                <div class="menu_dish_card">
                    <div class="menu_dish_card_inner">
                        {% for dish in category.dish_set.all %}
                            <div class="menu_dish_item">
                                <div class="menu_dish_name">{{ dish.name }}</div>
                                <img class="menu_dish_card_image" src="{{ dish.photo.url }}" alt="{{ dish.name }}">
                                <div class="menu_dish_price">{{ dish.price }} сум</div>
                                <div class="add_to_basket">
                                    <form method="POST" action="{% url 'add_to_basket' dish.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="add_to_basket_btn">Добавить в корзину</button>
                                    </form>
                                </div>
                            </div>
                        {% empty %}
                            <p>Нет блюд в этой категории.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

project/app/templates/app/customer/order_confirmation.html
{% extends 'app/layouts/base.html' %}

{% block content %}
<h2>Заказ успешно создан!</h2>
<p>Ваш заказ был успешно оформлен. Мы скоро с вами свяжемся!</p>
<a href="{% url 'menu' %}" class="back_button">Вернуться в меню</a>
{% endblock %}